config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'registrations'
  }

  resource :dashboard
  resources :projects do
    resources :bugs
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    root to: "devise/sessions#new"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bug.rb
class Bug < ApplicationRecord
    enum :status, [:created, :assigned, :resolved]
    belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
    enum :status, [ :open, :closed ]
    validates :title, :description, presence: true
    has_one_attached :image
    has_many :bugs, dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
        :lockable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    




    protected

    def after_sign_in_path_for(_resource)
        dashboard_path
    end

    def after_sign_up_path_for(_resource)
        dashboard_path
    end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
    before_action :set_project, only: %i[index new create] 
    def index
        @bugs = @project.bugs
    end

    def new
        @bug = @project.bugs.build
    end

    def create
        @bug = @project.bugs.create(bug_params)
        redirect_to project_bugs_path(@project.id)
    end

    def edit

    end

    def update
        if @bug.update!(bug_params)
            redirect_to bugs_path
        else
            render :edit
        end
    end

    def destroy
        @bug.destroy
    end

    def show
    end

    private

    def set_project
        @project = Project.find_by(id: params['project_id'])
    end
    def set_bug
        @bug = Bug.find(params[:id])
    end

    def bug_params
        params.require(:bug).permit(:title, :description, :status)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    def show
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: %i[show edit update destroy]

    def index
        @projects = Project.order(:id)
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)
        if @project.save
            redirect_to projects_path
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @project.update!(project_params)
            redirect_to projects_path
        else
            render :edit
        end
    end

    def destroy
        @project.destroy
    end

    private

    def set_project
        @project = Project.find(params[:id])
    end

    def project_params
        params.require(:project).permit(:title, :description, :status, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # POST /resource

def create
    build_resource(sign_up_params)
    resource.save
    resource.add_role params['role']
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/bugs/_form.html.erb
<div style="width:60%;">
<%= form_with(model: [project, bug]) do |form| %>
    <div class="row g-3">
    <%= form.label :name, "Project Title:", :class=>"form-label" %>
    <%= form.text_field :title, :class=>"form-control" %>
<br/>
    <%= form.label "Project Description", :class=>"form-label" %>
    <%= form.text_area :description, :class=>"form-control" %>
    <br/>

    <%= form.label "Status" %>
    <%= form.select :status, [["Created","created"],["Assigned","assigned"], ["Resolved","resolved"]],  {promt: "Select Status"}, {class:"form-select"} %>
    <br/>

    <%= form.submit "Add", :class=>"form-control btn btn-primary" %>
    </div>
  <% end %>
  </div>

app/views/bugs/edit.html.erb
<div class="container">
<main>
<div class="py-5" style="display: flex;
flex-direction: column;
align-items: center;">
<h1>Edit This Project</h1>
<%= render 'form', project: @project %>
</div>
</main>
</div>

app/views/bugs/index.html.erb
<div class="container">
<main>
<div class="text-center py-5">
<h1> Welcome to the bugs </h1>
<%= link_to "New Bug", new_project_bug_path %>
<table class="table table-striped">
<thead class="thead-dark">
<tr>
<th scope="col">#</th>
<th scope="col">Title</th>
<th scope="col">Description</th>
<th scope="col">Status</th>
<th scope="col">Action</th>

</tr>
</thead>
<tbody>
<% @bugs.each_with_index do |bug, index| %>
<tr>
<th scope="row"><%= index+1 %></th>
<td><%= bug.title %></td>
<td><%= bug.description %></td>
<td><%= bug.status %></td>
<td>
 <%= link_to "Edit", edit_project_bug_path(@project.id, bug) %>
</td>

</tr>
<% end %>
</tbody>
</table>
</div>
</main>
</div>

app/views/bugs/new.html.erb
<div class="container">
<main>
<div class="py-5" style="display: flex;
flex-direction: column;
align-items: center;">
<h1>Create New Bug</h1>
<%= render 'form', project: @project, bug:@bug %>

</div>
</main>
</div>

app/views/bugs/show.html.erb
<h1>Title: <%= @project.title %></h1>
<br/>
<% if @project.image.attached?  %>
    <img width="500px" src="<%= (url_for(@project.image)) %>" />
<% end %>
<br/>
<p><%= @project.description %></p>
<span><%= @project.status %></span>

app/views/dashboards/show.html.erb
<main>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
<link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/> <!--Replace with your tailwind.css once created-->
<link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet"> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js" integrity="sha256-xKeoJ50pzbUGkpQxDYHD7o7hxe0LaOGeguUidbq6vis=" crossorigin="anonymous"></script>

    <div class="flex flex-col md:flex-row -mt-8">
      
        <section>
            <div id="main" class="main-content flex-1 bg-gray-100 mt-12 md:mt-2 pb-24 md:pb-5">

                <div class="bg-gray-800 pt-3">
                    <div class="bg-gradient-to-r from-blue-900 to-gray-800 p-4 shadow text-2xl text-white">
                        <h1 class="font-bold pl-2">Analytics</h1>
                    </div>
                </div>

                <div class="flex flex-wrap">
                    <div class="w-full md:w-1/2 xl:w-1/3 p-6">
                        <!--Metric Card-->
                        <div class="bg-gradient-to-b from-green-200 to-green-100 border-b-4 border-green-600 rounded-lg shadow-xl p-5">
                            <div class="flex flex-row items-center">
                                <div class="flex-shrink pr-4">
                                    <div class="rounded-full p-5 bg-green-600"><i class="fa fa-wallet fa-2x fa-inverse"></i></div>
                                </div>
                                <div class="flex-1 text-right md:text-center">
                                    <h2 class="font-bold uppercase text-gray-600">Total Projects</h2>
                                   <p class="font-bold text-3xl"><%= Project.all.count %> <span class="text-green-500"><i class="fas fa-caret-up"></i></span></p>
                                </div>
                            </div>
                        </div>
                        <!--/Metric Card-->
                    </div>
                    <div class="w-full md:w-1/2 xl:w-1/3 p-6">
                        <!--Metric Card-->
                        <div class="bg-gradient-to-b from-pink-200 to-pink-100 border-b-4 border-pink-500 rounded-lg shadow-xl p-5">
                            <div class="flex flex-row items-center">
                                <div class="flex-shrink pr-4">
                                    <div class="rounded-full p-5 bg-pink-600"><i class="fas fa-users fa-2x fa-inverse"></i></div>
                                </div>
                                <div class="flex-1 text-right md:text-center">
                                    <h2 class="font-bold uppercase text-gray-600">Total Users</h2>
                                    <p class="font-bold text-3xl"><%= User.all.count %> <span class="text-pink-500"><i class="fas fa-exchange-alt"></i></span></p>
                                </div>
                            </div>
                        </div>
                        <!--/Metric Card-->
                    </div>
                    <div class="w-full md:w-1/2 xl:w-1/3 p-6">
                        <!--Metric Card-->
                        <div class="bg-gradient-to-b from-yellow-200 to-yellow-100 border-b-4 border-yellow-600 rounded-lg shadow-xl p-5">
                            <div class="flex flex-row items-center">
                                <div class="flex-shrink pr-4">
                                    <div class="rounded-full p-5 bg-yellow-600"><i class="fas fa-user-plus fa-2x fa-inverse"></i></div>
                                </div>
                                <div class="flex-1 text-right md:text-center">
                                    <h2 class="font-bold uppercase text-gray-600">New Users</h2>
                                    <p class="font-bold text-3xl">2 <span class="text-yellow-600"><i class="fas fa-caret-up"></i></span></p>
                                </div>
                            </div>
                        </div>
                        <!--/Metric Card-->
                    </div>
                    <div class="w-full md:w-1/2 xl:w-1/3 p-6">
                        <!--Metric Card-->
                        <div class="bg-gradient-to-b from-blue-200 to-blue-100 border-b-4 border-blue-500 rounded-lg shadow-xl p-5">
                            <div class="flex flex-row items-center">
                                <div class="flex-shrink pr-4">
                                    <div class="rounded-full p-5 bg-blue-600"><i class="fas fa-server fa-2x fa-inverse"></i></div>
                                </div>
                                <div class="flex-1 text-right md:text-center">
                                    <h2 class="font-bold uppercase text-gray-600">Server Uptime</h2>
                                    <p class="font-bold text-3xl">152 days</p>
                                </div>
                            </div>
                        </div>
                        <!--/Metric Card-->
                    </div>
                    <div class="w-full md:w-1/2 xl:w-1/3 p-6">
                        <!--Metric Card-->
                        <div class="bg-gradient-to-b from-indigo-200 to-indigo-100 border-b-4 border-indigo-500 rounded-lg shadow-xl p-5">
                            <div class="flex flex-row items-center">
                                <div class="flex-shrink pr-4">
                                    <div class="rounded-full p-5 bg-indigo-600"><i class="fas fa-tasks fa-2x fa-inverse"></i></div>
                                </div>
                                <div class="flex-1 text-right md:text-center">
                                    <h2 class="font-bold uppercase text-gray-600">To Do List</h2>
                                    <p class="font-bold text-3xl">7 tasks</p>
                                </div>
                            </div>
                        </div>
                        <!--/Metric Card-->
                    </div>
                    <div class="w-full md:w-1/2 xl:w-1/3 p-6">
                        <!--Metric Card-->
                        <div class="bg-gradient-to-b from-red-200 to-red-100 border-b-4 border-red-500 rounded-lg shadow-xl p-5">
                            <div class="flex flex-row items-center">
                                <div class="flex-shrink pr-4">
                                    <div class="rounded-full p-5 bg-red-600"><i class="fas fa-inbox fa-2x fa-inverse"></i></div>
                                </div>
                                <div class="flex-1 text-right md:text-center">
                                    <h2 class="font-bold uppercase text-gray-600">Issues</h2>
                                    <p class="font-bold text-3xl">3 <span class="text-red-500"><i class="fas fa-caret-up"></i></span></p>
                                </div>
                            </div>
                        </div>
                        <!--/Metric Card-->
                    </div>
                </div>
                </div>
                </section>
            </div>
        </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugzilla</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
  <% if user_signed_in? %>
  <%= link_to "BugZilla", dashboard_path, :class =>"navbar-brand text-emerald-500	" %>
  <% else %>
  <%= link_to "BugZilla", root_path, :class =>"navbar-brand text-emerald-500" %>
  <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
              <%= link_to "Projects", projects_path,  :class =>"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        
      </ul>
    </div>
    <div class="text-end d-flex flex-wrap align-items-center justify-content-center" style="gap:10px;" >
    <% if user_signed_in? %>
    <p class="text text-info">You are logged in as '<%= current_user.roles.first.name.capitalize %>'</p>
    <%= link_to "New Project", new_project_path, :class => "me-2 btn btn-outline-warning" %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, :class=>"btn btn-outline-danger" %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, :class=>"btn btn-outline-danger" %> 
      <%= link_to "Register", new_user_registration_path, :class => "me-2 btn btn-outline-warning" %>
    <% end%>

    </div>
  </div>
</nav>
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
   
      <%= yield %>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>

</html>

app/views/projects/_form.html.erb
<div style="width:60%;">
<%= form_with(model: project) do |form| %>
    <div class="row g-3">
    <%= form.label :name, "Project Title:", :class=>"form-label" %>
    <%= form.text_field :title, :class=>"form-control" %>
<br/>
    <%= form.label "Project Description", :class=>"form-label" %>
    <%= form.text_area :description, :class=>"form-control" %>
    <br/>

    <%= form.label "Status" %>
    <%= form.select :status, [["Open","open"],["Closed","closed"]], {promt: "Select Status"}, {class:"form-select"} %>
    <br/>

    <%= form.label "Featured Image", :class=>"form-label" %>
    <%= form.file_field :image, :class=>"form-control" %>
    <br/>

    <%= form.submit "Add", :class=>"form-control btn btn-primary" %>
    </div>
  <% end %>
  </div>

app/views/projects/index.html.erb
<div class="container">
<main>
<div class="text-center py-5">
<h1> Welcome to the projects </h1>
<table class="table table-striped">
<thead class="thead-dark">
<tr>
<th scope="col">#</th>
<th scope="col">Title</th>
<th scope="col">Description</th>
<th scope="col">Status</th>
<th scope="col">Action</th>

</tr>
</thead>
<tbody>
<% @projects.each_with_index do |project, index| %>
<tr>
<th scope="row"><%= index+1 %></th>
<td><%= project.title %></td>
<td><%= project.description %></td>
<td><%= project.status %></td>
<td>
<%= link_to "Edit", edit_project_path(project) %>
</td>

</tr>
<% end %>
</tbody>
</table>
</div>
</main>
</div>

app/views/projects/new.html.erb
<div class="container">
<main>
<div class="py-5" style="display: flex;
flex-direction: column;
align-items: center;">
<h1>Create New Project</h1>
<%= render 'form', project: @project %>

</div>
</main>
</div>